### PR TITLE
fix issue with scroll synchronisation

### LINKED ISSUE #86: Navigation does not update on scrolling contents
## What happened
When the app opens, all the navigation tags on the left hand side are collapsed by default.

When scrolling the contents on the right hand side, if the corresponding tag is expanded, then the active tag method will be highlighted accordingly.

However, if the corresponding tag is collapsed, scrolling the contents does not have any effect.

## Expected
Even when the tag was collapsed, it should be automatically expanded in this case.

### PR DESCRIPTION
**Pull request by quangkhoa**
resolve #86

### CODE REVIEW

File: src/handlers/BaseHandler.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ class BaseHandler extends Component {
     const openApiUrl = this.props.location.query.url
     const parserType = this.props.parserType
     this.props.getDefinition(openApiUrl, parserType)
-    configureAnchors({ offset: 10 })
+    configureAnchors({ offset: -10, scrollDuration: 100 })
```
Comment (brendo) [inline src/handlers/BaseHandler.js:18]: I had to add `keepLastAnchorHash: true` to prevent the hash from being cleared each time I scrolled. Can you confirm if that happens for you too?

Comment (quangkhoa) [reply src/handlers/BaseHandler.js:18]: No, I don't have that one, and it doesn't clear the hash when I scroll

Comment (brendo) [reply src/handlers/BaseHandler.js:18]: Couldn't reproduce when I retried with a fresh webpack build. Merging!
