### PR TITLE
misc small fixes

### LINKED ISSUE #47: Misc small fixes
- Remove description under `Request`, e.g.

image

- Navigation methods: separate method type from method description e.g.
image

- Move response description to the same line as response code, e.g.
image

- Remove highlighting of property description when property is object, e.g.
image

### PR DESCRIPTION
**Pull request by quangkhoa**
resolve #47

### CODE REVIEW

File: src/components/Property/Property.js [hunk 1]
```diff
@@ -25,17 +25,17 @@ export default class Property extends Component {
...
-        <td className="property-name">
+        <td className={classNames('property-name', {
+          'property--isclickable': isClickable,
+          last: isLast
+        })}>
           <span>{name}</span>
           {isClickable &&
-            <Indicator className="property-indicator" status={status} />
-        }
+          <Indicator className="property-indicator" status={status}/>
```
Comment (phlorie) [inline src/components/Property/Property.js]: There needs to be some indentation here

Comment (quangkhoa) [reply src/components/Property/Property.js]: updated
